# Check action for development
on: [push, pull_request]

jobs:
  ncu_report:
    runs-on: ubuntu-latest
    name: npm-check-updates report
    steps:
      - uses: actions/checkout@v2  
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prComment
      - run: echo "Comment URL - ${{ steps.prComment.outputs.commentUrl }}"
        if: steps.prComment.outputs.commentUrl